# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ghcPaths, QuickCheck, tasty, transformers }:

cabal.mkDerivation (self: {
  pname = "ML4HS";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ ghcPaths QuickCheck transformers ];
  testDepends = [ ghcPaths tasty transformers ];
  meta = {
    homepage = "http://gitorious.org/ml4hs";
    description = "Machine learning applied to Haskell source code";
    license = self.stdenv.lib.licenses.publicDomain;
    platforms = self.ghc.meta.platforms;
  };
})
