# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, Cabal, haskellNames, haskellPackages, haskellSrcExts
, tasty, transformers
}:

cabal.mkDerivation (self: {
  pname = "ML4HS";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    Cabal haskellNames haskellPackages haskellSrcExts
  ];
  testDepends = [
    Cabal haskellNames haskellPackages haskellSrcExts tasty
    transformers
  ];
  meta = {
    homepage = "http://gitorious.org/ml4hs";
    description = "Machine learning applied to Haskell source code";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
