# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ghcPaths, QuickCheck, tasty, tipHaskellFrontend, tipLib
, transformers
}:

cabal.mkDerivation (self: {
  pname = "ML4HS";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    ghcPaths QuickCheck tipHaskellFrontend tipLib transformers
  ];
  testDepends = [ ghcPaths tasty transformers ];
  meta = {
    homepage = "http://gitorious.org/ml4hs";
    description = "Machine learning applied to Haskell source code";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
